services:
  interface:
    build:
      context: .
      dockerfile: ./deploy/bot_interface/Dockerfile
    container_name: discount-alert-bot-interface
    depends_on: &depends_on
      broker:
        condition: service_healthy
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    env_file:  &env_file
      - .env
    environment: &environment
      BROKER_HOST: discount-alert-bot-broker
      BROKER_PORT: 5672
      DB_HOST: discount-alert-bot-db
      DB_PORT: 5432
    restart: always

  engine:
    build:
      context: .
      dockerfile: ./deploy/bot_engine/Dockerfile
    container_name: discount-alert-bot-engine
    depends_on: *depends_on
    env_file: *env_file
    environment: *environment
    restart: always

  migrator:
    build:
      context: .
      dockerfile: ./deploy/migrator/Dockerfile
    container_name: discount-alert-bot-migrator
    depends_on:
      db:
        condition: service_healthy
    env_file: *env_file
    environment: *environment
    restart: "no"
    command: ["upgrade", "head"]

  broker:
    build: ./deploy/broker
    container_name: discount-alert-bot-broker
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${BROKER_VHOST}
    ports:
      - "${BROKER_PORT}:5672"
      - "1${BROKER_PORT}:15672"
    volumes:
      - discount-alert-bot-broker-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

  db:
    image: postgres:14
    container_name: discount-alert-bot-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - discount-alert-bot-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  discount-alert-bot-broker-data:
  discount-alert-bot-db-data:
