"""make products.initial_price string

Revision ID: 8cee915e28a0
Revises: ca80d795b8e6
Create Date: 2024-11-18 21:48:28.899090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cee915e28a0"
down_revision: Union[str, None] = "ca80d795b8e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "initial_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_column("products", "last_price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("last_price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "products",
        "initial_price",
        existing_type=sa.String(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
