"""make users.telegram_id integer

Revision ID: bd960ac97553
Revises: 8cee915e28a0
Create Date: 2024-11-18 22:07:02.045651

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd960ac97553"
down_revision: Union[str, None] = "8cee915e28a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("""
        ALTER TABLE users
        ALTER COLUMN telegram_id TYPE INTEGER
        USING telegram_id::INTEGER
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text("""
        ALTER TABLE users
        ALTER COLUMN telegram_id TYPE VARCHAR
        USING telegram_id::TEXT
    """)
    )
    # ### end Alembic commands ###
