"""add index to products.link column

Revision ID: ca80d795b8e6
Revises: 91a59140ddb5
Create Date: 2024-11-18 20:42:56.884337

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca80d795b8e6"
down_revision: Union[str, None] = "91a59140ddb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_products_link"), "products", ["link"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_link"), table_name="products")
    # ### end Alembic commands ###
